/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.github.asifmujteba.easyvolleysample.Models;

import org.parceler.Parcel;

@Parcel
public class Data {
	String brand;

 	public void setBrand(String brand) {
		this.brand = brand;
	}

	public String getBrand() {
		return brand;
	}

	String sku;

 	public void setSku(String sku) {
		this.sku = sku;
	}

	public String getSku() {
		return sku;
	}

	String max_price;

 	public void setMax_price(String max_price) {
		this.max_price = max_price;
	}

	public String getMax_price() {
		return max_price;
	}

	String url;

 	public void setUrl(String url) {
		this.url = url;
	}

	public String getUrl() {
		return url;
	}

	String price;

 	public void setPrice(String price) {
		this.price = price;
	}

	public String getPrice() {
		return price;
	}

	String name;

 	public void setName(String name) {
		this.name = name;
	}

	public String getName() {
		return name;
	}


}