/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.github.asifmujteba.easyvolleysample.Models;

import org.parceler.Parcel;

@Parcel
public class ImageElement {
	String path;

 	public void setPath(String path) {
		this.path = path;
	}

	public String getPath() {
		return path;
	}

	String format;

 	public void setFormat(String format) {
		this.format = format;
	}

	public String getFormat() {
		return format;
	}

	String height;

 	public void setHeight(String height) {
		this.height = height;
	}

	public String getHeight() {
		return height;
	}

	String width;

 	public void setWidth(String width) {
		this.width = width;
	}

	public String getWidth() {
		return width;
	}


}